[bot]
server: localhost
chat_id: 	386518931
bot_token: 5042592266:AAHH7ztxrdbCWYJnPVXn0C4SH1ycQk6UjoI
log_path: /home/pi/klipper_logs

[camera]
host: http://localhost:8080/?action=stream
fps: 20
flip_vertically: false
flip_horizontally: true
video_duration: 10
picture_quality: high

[progress_notification]
percent: 5
height: 5
time: 600
#min_delay_between_notifications: 600


[timelapse]
cleanup: true
height: 0.2
time: 5
target_fps: 30	
